App\Entity\User:
    type: entity
    table: user
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            scale: 0
            length: 180
            unique: true
            nullable: false
            precision: 0
        roles:
            type: json
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        password:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
